version: '3'
services:
  annual_declaration:
    image: postgres:latest
    environment:
      - POSTGRES_USER=ad_user
      - POSTGRES_PASSWORD=ad_user
      - POSTGRES_DB=annual_declaration
    volumes:
      - ./src/main/resources/schema_docker.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5738:5432"
